Fix a race in Serve()
.Serve() set the registry on the server object, but tests were calling
.Serve then writing to values underneath the registry.

Moved the registry creation to .NewServer() so that the registry would
definitely exist

```
GORACE="strip_path_prefix=$(pwd)/" go test -run TestClientRequestWithUnknownMailbox -race ./...
test-namespace-5577006791947779410: 2019/09/24 09:41:24 registry: 127-0-0-1-39689: keep alive responded with heartbeat TTL: 60s
==================
WARNING: DATA RACE
Read at 0x00c0001108f0 by goroutine 6:
  github.com/lytics/grid.TestClientRequestWithUnknownMailbox()
      client_test.go:154 +0x23c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Previous write at 0x00c0001108f0 by goroutine 15:
  github.com/lytics/grid.(*Server).Serve()
      server.go:97 +0x492
  github.com/lytics/grid.bootstrapClientTest.func1()
      client_test.go:546 +0x50

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:104 +0x222

Goroutine 15 (running) created at:
  github.com/lytics/grid.bootstrapClientTest()
      client_test.go:545 +0x4c6
  github.com/lytics/grid.TestClientRequestWithUnknownMailbox()
      client_test.go:143 +0x53
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
==================
WARNING: DATA RACE
Write at 0x00c000234120 by goroutine 6:
  sync/atomic.CompareAndSwapInt32()
      /usr/local/go/src/runtime/race_amd64.s:293 +0xb
  sync.(*Mutex).Lock()
      /usr/local/go/src/sync/mutex.go:74 +0x4d
  github.com/lytics/grid/registry.(*Registry).Register()
      registry/registry.go:377 +0xa6
  github.com/lytics/grid.TestClientRequestWithUnknownMailbox()
      client_test.go:154 +0x2f1
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163

Previous write at 0x00c000234120 by goroutine 15:
  github.com/lytics/grid.(*Server).Serve()
      registry/registry.go:114 +0x2e2
  github.com/lytics/grid.bootstrapClientTest.func1()
      client_test.go:546 +0x50

Goroutine 6 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:104 +0x222

Goroutine 15 (running) created at:
  github.com/lytics/grid.bootstrapClientTest()
      client_test.go:545 +0x4c6
  github.com/lytics/grid.TestClientRequestWithUnknownMailbox()
      client_test.go:143 +0x53
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:865 +0x163
==================
test-namespace-5577006791947779410: 2019/09/24 09:41:27 registry: 127-0-0-1-39689: keep alive closed
--- FAIL: TestClientRequestWithUnknownMailbox (3.28s)
    testing.go:809: race detected during execution of test
FAIL
FAIL	github.com/lytics/grid	3.294s
ok  	github.com/lytics/grid/codec	(cached) [no tests to run]
?   	github.com/lytics/grid/codec/protomessage	[no test files]
?   	github.com/lytics/grid/examples/hello	[no test files]
?   	github.com/lytics/grid/examples/requestreply	[no test files]
ok  	github.com/lytics/grid/registry	(cached) [no tests to run]
ok  	github.com/lytics/grid/ring	(cached) [no tests to run]
?   	github.com/lytics/grid/testetcd	[no test files]
```